name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Using a single Python version for simplicity

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pymongo  # Explicitly install pymongo

    - name: Run Tests
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: |
        python manage.py test
